-- EmoteControl - Common Pack

local _, EC = ...

if not EC or type(EC.RegisterPack) ~= "function" then
    return
end

EC:RegisterPack({
    id = "common",
    name = "Common Pack",
    triggers = {
        {
            id = "player_died",
            event = "PLAYER_DEAD",
            cooldown = 10,
            category = "general",
            channel = "EMOTE",
            messages = {
                "falls in {zone}.",
                "hits the floor in {subzone}.",
                "was defeated in {zone}.",
                "meets an untimely end.",
                "adds another death to the tally.",
            },
        },
        {
            id = "player_resurrected",
            event = "PLAYER_ALIVE",
            cooldown = 10,
            category = "general",
            channel = "EMOTE",
            messages = {
                "returns to life in {zone}.",
                "shakes off the grave dust.",
                "stands again in {subzone}.",
                "is back in action.",
                "gets a second chance.",
            },
        },
        {
            id = "player_resurrected_by_other",
            event = "RESURRECT_REQUEST",
            cooldown = 7,
            category = "general",
            channel = "SAY",
            messages = {
                "Thanks for the rez!",
                "Appreciate the resurrection.",
                "Back up—thank you!",
                "I owe you for that rez.",
                "Saved by the res. Thanks!",
            },
        },
        {
            id = "combat_start",
            event = "PLAYER_REGEN_DISABLED",
            cooldown = 5,
            category = "general",
            channel = "EMOTE",
            messages = {
                "draws their weapon.",
                "enters combat stance.",
                "prepares to engage {target}.",
                "steps into battle.",
                "readies for the fight.",
            },
        },
        {
            id = "combat_end",
            event = "PLAYER_REGEN_ENABLED",
            cooldown = 5,
            category = "general",
            channel = "EMOTE",
            messages = {
                "sheathes their weapon.",
                "catches their breath.",
                "relaxes after the fight.",
                "stands victorious.",
                "lets the adrenaline fade.",
            },
        },
        {
            id = "level_up",
            event = "PLAYER_LEVEL_UP",
            cooldown = 7,
            category = "general",
            channel = "SAY",
            messages = {
                "Level {level}!",
                "Ding! Now level {level}.",
                "Another level: {level}.",
                "Leveled up to {level}.",
                "Power grows—level {level}.",
            },
        },
        {
            id = "achievement_earned",
            event = "ACHIEVEMENT_EARNED",
            cooldown = 6,
            category = "general",
            channel = "SAY",
            messages = {
                "Achievement unlocked: {achievement}!",
                "Earned {achievement}.",
                "Got achievement {achievement}.",
                "Another achievement: {achievement}.",
                "Achievement complete: {achievement}.",
            },
        },
        {
            id = "loot_epic_general",
            event = "CHAT_MSG_LOOT",
            cooldown = 6,
            category = "general",
            channel = "SAY",
            messages = {
                "Looted: {loot}",
                "Picked up {loot}.",
                "Got loot: {loot}.",
                "Score! {loot}",
                "Shiny loot: {loot}.",
            },
        },
        {
            id = "party_invite_accepted_general",
            event = "GROUP_JOINED",
            cooldown = 6,
            category = "general",
            channel = "PARTY",
            messages = {
                "Joined the group.",
                "Here and ready.",
                "Group up!",
                "Let’s do this.",
                "Ready to go.",
            },
        },
        {
            id = "party_left_general",
            event = "GROUP_LEFT",
            cooldown = 4,
            category = "general",
            channel = "EMOTE",
            messages = {
                "leaves the group.",
                "heads off solo.",
                "parts ways with the party.",
                "steps away from the group.",
                "moves on from the party.",
            },
        },
        {
            id = "zone_changed",
            event = "ZONE_CHANGED_NEW_AREA",
            cooldown = 5,
            category = "general",
            channel = "EMOTE",
            messages = {
                "arrives in {zone}.",
                "enters {zone}.",
                "travels to {zone}.",
                "sets foot in {zone}.",
                "reaches {zone}.",
            },
        },
        {
            id = "entered_dungeon",
            event = "PLAYER_ENTERING_WORLD",
            cooldown = 5,
            category = "general",
            channel = "INSTANCE",
            messages = {
                "Entering {zone}.",
                "Ready for {zone}.",
                "Here we go in {zone}.",
                "Let’s clear this place.",
                "Dungeon time.",
            },
        },
        {
            id = "combat_crit",
            event = "COMBAT_CRITICAL_HIT",
            cooldown = 6,
            category = "general",
            channel = "EMOTE",
            messages = {
                "lands a critical hit on {target}.",
                "strikes {target} critically.",
                "delivers a crushing blow.",
                "hits hard with a crit.",
                "critical strike landed.",
            },
        },
        {
            id = "combat_dodged",
            event = "COMBAT_DODGED",
            cooldown = 4,
            category = "general",
            channel = "EMOTE",
            messages = {
                "dodges the attack.",
                "sidesteps cleanly.",
                "avoids the blow.",
                "evades at the last moment.",
                "moves out of harm’s way.",
            },
        },
        {
            id = "combat_parried",
            event = "COMBAT_PARRIED",
            cooldown = 4,
            category = "general",
            channel = "EMOTE",
            messages = {
                "parries the attack.",
                "deflects the strike.",
                "turns the blow aside.",
                "blocks with perfect timing.",
                "repels the attack.",
            },
        },
        {
            id = "combat_interrupted",
            event = "COMBAT_INTERRUPTED",
            cooldown = 6,
            category = "general",
            channel = "SAY",
            messages = {
                "Interrupted!",
                "Spell stopped.",
                "No casting that!",
                "Interrupt landed.",
                "Shut that down.",
            },
        },
        {
            id = "mail_opened",
            event = "MAIL_SHOW",
            cooldown = 8,
            category = "utility",
            channel = "EMOTE",
            messages = {
                "checks the mailbox.",
                "sorts through the mail.",
                "opens new mail.",
                "collects deliveries.",
                "reviews the inbox.",
            },
        },
        {
            id = "bank_opened",
            event = "BANKFRAME_OPENED",
            cooldown = 10,
            category = "utility",
            channel = "EMOTE",
            messages = {
                "opens the bank.",
                "accesses stored items.",
                "checks the vault.",
                "manages bank storage.",
                "reviews bank inventory.",
            },
        },
        {
            id = "merchant_opened",
            event = "MERCHANT_SHOW",
            cooldown = 10,
            category = "utility",
            channel = "EMOTE",
            messages = {
                "browses the merchant’s wares.",
                "sells a few items.",
                "checks vendor stock.",
                "haggles with the merchant.",
                "shops for supplies.",
            },
        },
        {
            id = "taxi_taken",
            event = "TAXIMAP_OPENED",
            cooldown = 15,
            category = "utility",
            channel = "EMOTE",
            messages = {
                "consults the flight map.",
                "plots a flight route.",
                "checks the taxi network.",
                "chooses a destination.",
                "prepares for a flight.",
            },
        },
        {
            id = "repair_needed",
            event = "REPAIR_NEEDED",
            cooldown = 60,
            category = "utility",
            channel = "SAY",
            messages = {
                "Need repairs soon.",
                "Gear needs fixing.",
                "Armor is battered.",
                "Time to repair.",
                "Repairs required.",
            },
        },
        {
            id = "bag_full",
            event = "BAG_FULL",
            cooldown = 30,
            category = "utility",
            channel = "SAY",
            messages = {
                "Bags are full.",
                "No bag space left.",
                "Inventory is full.",
                "Need to clear bags.",
                "Bags are stuffed.",
            },
        },
        {
            id = "loot_epic_flavor",
            event = "CHAT_MSG_LOOT",
            cooldown = 30,
            category = "flavor",
            channel = "SAY",
            messages = {
                "Epic loot: {loot}!",
                "That’s a shiny {loot}.",
                "Wow, {loot} dropped!",
                "Loot luck! {loot}.",
                "Finally: {loot}.",
            },
        },
        {
            id = "party_invite_accepted_flavor",
            event = "GROUP_JOINED",
            cooldown = 30,
            category = "flavor",
            channel = "PARTY",
            messages = {
                "Party time.",
                "Let’s roll.",
                "Group assembled.",
                "Ready for action.",
                "Here we go.",
            },
        },
        {
            id = "party_left_flavor",
            event = "GROUP_LEFT",
            cooldown = 30,
            category = "flavor",
            channel = "EMOTE",
            messages = {
                "waves goodbye.",
                "heads out.",
                "takes their leave.",
                "steps away from the group.",
                "moves on.",
            },
        },
    },
})
