-- EmoteControl - Death Knight Pack

local _, EC = ...

if not EC or type(EC.RegisterPack) ~= "function" then
  return
end

-- Design notes:
-- - Uses spellName so the core can resolve IDs at runtime.
-- - Cooldowns are intentionally higher for rotational spells to avoid spam.

EC:RegisterPack({
  id = "deathknight",
  name = "Death Knight Pack",
  triggers = {
    -- Emote flavor triggers
    {
      id = "dk_combat_start",
      event = "PLAYER_REGEN_DISABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      conditions = { class = "DEATHKNIGHT", unit = "player" },
      messages = {
        "unsheathes their runeblade, frost and death awakening.",
        "calls upon unholy power, ready to rend.",
        "enters combat with grim determination.",
        "channels the power of the Lich King.",
        "prepares to spread death and decay.",
        "The death knight rises to the challenge.",
        "Unholy runes awaken with purpose.",
        "The fallen shall rise or fall further.",
        "Death calls. The knight answers.",
        "Acherus whispers its dark blessing.",
        "Runes glow with eldritch power.",
        "The grip of death tightens.",
        "Plague and frost combine their assault.",
        "The scourge awakens in earnest.",
        "Cold purpose settles in.",
        "The pale rider stirs.",
        "Runeblade thirsts for battle.",
        "Death magic flows freely.",
        "The endless winter arrives.",
        "Unholy forces converge.",
        "The knight draws upon dark reserves.",
        "This ends with death.",
        "Cold fury ignites within.",
        "The shadow grows darker.",
        "A deathly aura surrounds.",
        "Runes pulse with malicious intent.",
        "The void answers the call.",
        "Frost and rot dance together.",
        "The death knight's dominion begins.",
        "Inevitable doom approaches.",
        "The scourge's power rises.",
        "Cold vengeance awakens.",
        "The pale lord enters the fray.",
        "Death's touch grows stronger.",
        "Undeath serves a purpose today.",
        "The frost bites deep.",
        "Plague spreads with purpose.",
        "The balance tips toward death.",
        "Liche's kiss bestows power.",
        "The endless hunger begins.",
      },
    },
    {
      id = "dk_combat_end",
      event = "PLAYER_REGEN_ENABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      conditions = { class = "DEATHKNIGHT", unit = "player" },
      messages = {
        "sheathes their runeblade, death satisfied.",
        "stands among fallen foes, victorious.",
        "nods coldly, another soul claimed.",
        "relaxes their grip, the reaping complete.",
        "stands firm, death eternal.",
        "The battle ends. Death remains.",
        "Acherus is satisfied for now.",
        "The runes fade to dormancy.",
        "Another chapter of horror written.",
        "The void recedes... for now.",
        "Cold satisfaction settles in.",
        "The frost dissipates slightly.",
        "Death's work continues eternally.",
        "The pale rider rests briefly.",
        "Plague and rot retreat reluctantly.",
        "The scourge hungers yet.",
        "Victory in death's name.",
        "The unholy tide ebbs.",
        "Another soul for the collection.",
        "The shadow lingers ominously.",
        "Runes dim but never sleep.",
        "Cold peace settles.",
        "The death knight waits patiently.",
        "Immortality claims another day.",
        "The endless hunger pauses.",
        "Darkness watches and waits.",
        "Death is satiated for now.",
        "The grip loosens only slightly.",
        "Undeath walks this world still.",
        "The pale lord surveys the carnage.",
        "Frost lingers in the air.",
        "The scourge's work is done... for now.",
        "Cold victory tastes eternal.",
        "The void remains forever patient.",
        "Another triumph of death magic.",
        "The knight stands among the fallen.",
        "Runes pulse with grim satisfaction.",
        "The balance shifts toward darkness.",
        "Death eternal is assured.",
        "The lich king's design continues.",
      },
    },

    -- Utility / Control
    {
      id = "dk_death_grip",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 10,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellID = 49576 },
      messages = {
        "Death Grip. Come here and regret it.",
        "<target>, your personal space has been revoked.",
        "Yoink. The Ebon Blade sends its regards.",
        "I brought you closer so we can have a meaningful argument.",
        "Gravity is a suggestion. I am the policy.",
        "Acherus says: get over here.",
        "If Midnight brings shadows, I bring traction.",
        "You were over there. That was a mistake.",
        "The void hungers. I oblige.",
        "Distance: eliminated. Regret: incoming.",
        "Your location preferences are irrelevant.",
        "<target>, please cease running.",
        "I have declared this space mine.",
        "Teleportation via necromantic force.",
        "The chains of death are invisible, but effective.",
        "You belong where I decide you belong.",
        "One does not simply escape death.",
        "Rune magic says: come here.",
        "Your journey to me begins now.",
        "The grip of the grave has no mercy.",
        "Acherus technology: working as intended.",
        "Physical laws bend before death magic.",
        "I am calling in a debt. Paid in proximity.",
        "<target>, you have been summoned.",
        "The runeblade reaches beyond its length.",
        "Distance is merely an illusion I destroy.",
        "Come closer. Let death embrace you.",
        "Your escape route: denied.",
        "The void extends its tendrils.",
        "To the reaper, all shall come.",
        "<target>, you are now my guest.",
        "The choreography of combat has changed.",
        "I control the space between us.",
        "Resist the grip? How quaint.",
        "Death has decided we meet here.",
        "The scourge's reach is infinite.",
        "<target>, your defensive position is compromised.",
        "Unholy runes pull. You comply.",
        "The cold brings everyone together.",
        "Acherus decrees: closer.",
        "No distance is safe from death.",
      },
    },
    {
      id = "dk_mind_freeze",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 8,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellID = 47528 },
      messages = {
        "Mind Freeze. Thoughts cancelled.",
        "Shhh. No more spells. Only silence.",
        "Your cast has been declined by necromantic customer support.",
        "That incantation was going somewhere embarrassing. I stopped it.",
        "Spell interrupted. Ego next.",
        "The runeblade says no.",
        "Void whispers can wait. You're done talking.",
        "I have applied a mandatory quiet moment.",
        "Your concentration has shattered.",
        "The icy touch breaks all focus.",
        "Silenced by the voice of death.",
        "Acherus demands: be quiet.",
        "Your magical voice has been muted.",
        "Frost chokes the incantation away.",
        "The scourge's interference: supreme.",
        "Spellcasting: suspended indefinitely.",
        "The void severs your connection.",
        "All your chanting just stopped. Cope.",
        "Mind locked. Communication prohibited.",
        "Death has no patience for your spells.",
        "Your arcane thoughts: frozen solid.",
        "The runeblade's interruption: brutal.",
        "Magical voice: permanently offline.",
        "Casting requires focus. I took both.",
        "The cold seeps into your consciousness.",
        "Acherus says: not today.",
        "Your spell just met an unfortunate end.",
        "Necromantic silence: absolute.",
        "The void consumes your incantation.",
        "I have decided your magic is done.",
        "Your mystical utterances: terminated.",
        "The frost locks your lips.",
        "Spellcraft interrupted by death itself.",
        "Your moment of power has passed.",
        "The scourge interrupts with authority.",
        "Magic: denied by superior power.",
        "Concentration: shattered beyond repair.",
        "Your spell dies before it lives.",
        "The reaper has spoken. Be silent.",
        "Mind and magic: both frozen.",
        "Acherus approved this interruption.",
      },
    },
    {
      id = "dk_chains_of_ice",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 10,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellID = 45524 },
      messages = {
        "Chains of Ice. Running is no longer a lifestyle.",
        "<target>, your mobility subscription has expired.",
        "Hold still. The cold has opinions.",
        "I brought winter in a convenient chain format.",
        "Slow down. I am trying to look menacing.",
        "Consider this a polite reminder to stop.",
        "Midnight can keep its darkness. I brought the chill.",
        "You are now speed-limited by decree.",
        "Your legs are now ornamental.",
        "The chains of winter bind you.",
        "<target>, enjoy standing still.",
        "Acherus has rendered you stationary.",
        "Your speed is now a memory.",
        "Frozen in place by ancient magic.",
        "The scourge keeps what it catches.",
        "Movement prohibited by icy mandate.",
        "Your flight: cancelled. Your chains: locked.",
        "The cold is patient. So am I.",
        "Escape velocity: insufficient.",
        "Death chains all who oppose it.",
        "Glacial shackles bind your limbs.",
        "Acherus decrees: be still.",
        "Your escape plan has frozen solid.",
        "The void reaches out in icy tendrils.",
        "Freedom: temporarily revoked.",
        "I have made you an anchor.",
        "Winter's chains are invisible but unbreakable.",
        "You stand because the cold demands it.",
        "The runeblade's frost holds you fast.",
        "Your legs remember only standing.",
        "The scourge's grip: eternal.",
        "<target>, you belong right there.",
        "Mobility is overrated anyway.",
        "The cold whispers: stay put.",
        "Chains of ice: fashion and function.",
        "Acherus has announced your immobility.",
        "Your momentum: stolen and converted to frost.",
        "The endless winter roots you here.",
        "Death keeps all who try to leave.",
        "Your speed has become property of the scourge.",
        "Be grateful you can still breathe.",
      },
    },
    {
      id = "dk_asphyxiate",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellID = 108194 },
      messages = {
        "Asphyxiate. Please pause all activities.",
        "Time out, <target>.",
        "I have scheduled your breathing for later.",
        "Hold that thought. And everything else.",
        "Stunned. For your own personal growth.",
        "Your freedom has been temporarily archived.",
        "If the Void is choking the Sunwell, I can multitask.",
        "Silence and stillness. Nice look on you.",
        "<target>, breath holding exercises begin now.",
        "The void crushes your will to resist.",
        "Consciousness check: failed.",
        "Your autonomic functions: overridden.",
        "Acherus says: be still and quiet.",
        "The death grip extends to your mind.",
        "Asphyxiation of the soul achieved.",
        "<target> is now in timeout.",
        "The scourge holds you in place.",
        "Your body disobeys. The void commands.",
        "Time: stopped. Life: suspended.",
        "The cold suffocates all resistance.",
        "Acherus has frozen your thoughts.",
        "Your actions are no longer yours.",
        "The void wraps around your mind.",
        "Stun duration: subjective.",
        "I have put you in the penalty box.",
        "<target>, contemplate your choices.",
        "The reaper's touch stills all motion.",
        "Consciousness fades. Silence prevails.",
        "Your free will: temporarily suspended.",
        "The scourge crushes your defenses.",
        "Acherus enforces compliance.",
        "<target> is stunned into submission.",
        "The void's grip is absolute.",
        "Your senses dim. The cold reigns.",
        "Asphyxiate: status effect applied.",
        "The endless winter silences all.",
        "You are now one with the void.",
        "Acherus demands: be still.",
        "The death that controls all strikes.",
        "<target>, the darkness takes you now.",
        "Your struggle ends. Your silence begins.",
      },
    },

    -- Defensives / Survival
    {
      id = "dk_anti_magic_shell",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellID = 48707 },
      messages = {
        "Anti-Magic Shell. Your spells are now decorative.",
        "Magic? In this economy? Not on me.",
        "Arcane nonsense detected. Firewall deployed.",
        "Your sorcery has been redirected to the trash.",
        "If Midnight brings Void magic, I brought receipts.",
        "Absorbing spells like it's a hobby.",
        "This is my 'no thank you' bubble.",
        "Shell up. Let the casters cope.",
        "The anti-magic shroud rises.",
        "Your casting: now purely theoretical.",
        "Necromantic immunity activated.",
        "Spell absorption: at maximum capacity.",
        "I have become spell-proof.",
        "Acherus shields all within the shell.",
        "Magic dies at my border.",
        "The void rejects your incantations.",
        "I am armored in anti-magic.",
        "Your spells scatter like snow.",
        "The scourge protects its own.",
        "Arcane energy: redistributed elsewhere.",
        "Acherus says: magic stops here.",
        "I have declared this a magic-free zone.",
        "Your casting attempts are futile.",
        "The shell reflects magical aggression.",
        "Enchantments shatter upon my barrier.",
        "I am cloaked in necrotic immunity.",
        "Magic withers in my presence.",
        "The void consumes your spellcraft.",
        "Your power finds no purchase here.",
        "Acherus approves this defense.",
        "The anti-magic field: impenetrable.",
        "I have become anathema to magic.",
        "Your arcane assault: absorbed.",
        "The reaper takes what casters offer.",
        "Spell absorption: a generous gift.",
        "I feast on your magical intent.",
        "Acherus feeds on your casting.",
        "The death knight knows no magic.",
        "The scourge's shell: absolute.",
        "Your magic is now my property.",
        "The endless winter freezes all spells.",
      },
    },
    {
      id = "dk_icebound_fortitude",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellID = 48792 },
      messages = {
        "Icebound Fortitude. I have become difficult.",
        "Pain is temporary. Spite is permanent.",
        "Fortitude online. Please submit damage in writing.",
        "I am now sturdier than your plans.",
        "If the Void tries to break me, it can take a number.",
        "I am a problem with armor.",
        "Icebound. Unbothered.",
        "Your burst window just became a suggestion.",
        "The frost hardens my body.",
        "I am encased in glacial power.",
        "Durability: ascended beyond normal limits.",
        "Acherus reinforces my defenses.",
        "The scourge protects what it claims.",
        "I have become an icy mountain.",
        "Fortitude cascades through my being.",
        "The void makes me unbreakable.",
        "Your damage meets my indifference.",
        "Acherus says: be hard.",
        "The cold has made me unyielding.",
        "I stand resolute in winter's grip.",
        "My resilience: legendary now.",
        "The reaper's blessing: perfect defense.",
        "I am hardened against all assault.",
        "The endless winter strengthens me.",
        "Acherus fortifies the devoted.",
        "The scourge's armor: invisible but mighty.",
        "You will not break me today.",
        "My body becomes ice incarnate.",
        "The frost locks all weakness away.",
        "Acherus says: endure.",
        "I have become unbending.",
        "Your attacks are merely tedious now.",
        "The void reinforces all defenses.",
        "Fortitude absolute. Pain irrelevant.",
        "I am glacial. You are not.",
        "The death knight does not falter.",
        "My resistance: legendary.",
        "Acherus approves this resilience.",
        "The scourge's durability: supreme.",
        "I have hardened my resolve.",
        "The cold keeps me standing tall.",
      },
    },
    {
      id = "dk_lichborne",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellID = 49039 },
      messages = {
        "Lichborne. Mortality status: optional.",
        "I have entered my spooky era.",
        "Fear effects are now unpaid interns.",
        "Behold: undead confidence.",
        "The Light looks away. I do not.",
        "If Midnight is about darkness, I'm ahead of schedule.",
        "Lichborne engaged. Please admire the vibes.",
        "I am technically alive enough.",
        "The lich form awakens within.",
        "Undeath makes me fearless.",
        "I have transcended mortal limitations.",
        "Acherus blesses me with lichdom.",
        "The void accepts the undead.",
        "Fear is for the living.",
        "The scourge ascends. I am elevated.",
        "Mortality: successfully rejected.",
        "I am undead and unbothered.",
        "The void transforms me completely.",
        "Lichborne power surges through me.",
        "Acherus says: become.",
        "I have shed mortal weakness.",
        "The endless winter is my natural state.",
        "Death no longer touches me.",
        "I am one with the lich.",
        "Fear effects: permanently unemployed.",
        "The scourge makes me eternal.",
        "Acherus grants undead serenity.",
        "I walk the lich's ancient path.",
        "Mortality means nothing now.",
        "The void fills where fear lived.",
        "I am lichborne and magnificent.",
        "Acherus watches over the undead.",
        "The reaper's blessing: undeath.",
        "I fear nothing. I am nothing to fear.",
        "The endless winter sustains me now.",
        "Acherus accepts the lichborn.",
        "The scourge elevates me.",
        "I transcend the mortal coil.",
        "Undeath is liberation.",
        "The void makes me whole.",
        "Lichborne: perfection achieved.",
      },
    },
    {
      id = "dk_death_strike",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellID = 49998 },
      messages = {
        "Death Strike. I paid for that health in violence.",
        "Borrowed life returned with interest.",
        "Your damage has been converted into my confidence.",
        "Siphon successful. Thank you for your contribution.",
        "I hit you, I heal me. Simple math.",
        "Self-care, but make it horrifying.",
        "Midnight can keep the despair. I prefer sustain.",
        "I am alive because I decided to be.",
        "The runeblade thirsts and drinks.",
        "Your vitality is now mine.",
        "Death feeds on itself.",
        "Acherus teaches self-preservation.",
        "I have stolen your life essence.",
        "The scourge sustains the devoted.",
        "Death magic heals the worthy.",
        "Your pain becomes my health.",
        "The void restores what I expend.",
        "I am a vampire of death.",
        "Acherus sustains his servants.",
        "The reaper's strike: always profitable.",
        "I am nourished by violence.",
        "Death strike: mutual benefit program.",
        "Your wounds heal me.",
        "The endless winter sustains.",
        "Acherus provides for the faithful.",
        "I drain and restore in one motion.",
        "The scourge knows only sustenance.",
        "Death pays dividends.",
        "I have converted injury into immunity.",
        "Acherus blesses the aggressive.",
        "The void fills all voids.",
        "Death strike: investment portfolio complete.",
        "Your defeat restores my vitality.",
        "The reaper always wins.",
        "I am sustained by the fallen.",
        "Acherus makes no waste.",
        "The scourge recycles everything.",
        "I strike and prosper.",
        "The endless winter feeds the faithful.",
        "Death sustains death eternal.",
        "Your life became mine. Be grateful.",
      },
    },

    -- Area / Presence
    {
      id = "dk_death_and_decay",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellID = 43265 },
      messages = {
        "Death and Decay. Please enjoy the ambiance.",
        "I have placed a bad circle on the ground. Do not stand in it.",
        "Acherus-approved landscaping.",
        "This area is now legally unpleasant.",
        "If Midnight brings a Voidstorm, I brought a doom puddle.",
        "Welcome to my hazard zone.",
        "The floor has been cursed. You're welcome.",
        "Ground effects: because subtlety is dead.",
        "The ground decays beneath your feet.",
        "I have painted the earth with death.",
        "Acherus marks this territory.",
        "The scourge desecrates all it touches.",
        "Decay spreads in concentric circles.",
        "This ground is now unholy.",
        "Death pools at my command.",
        "The void stains the earth black.",
        "Acherus has claimed this space.",
        "The endless winter kills the soil.",
        "I have made this place a graveyard.",
        "Decay: deployed and permanent.",
        "Acherus says: this is mine.",
        "The scourge's stain spreads.",
        "I have given this ground cancer.",
        "The void consumes the earth.",
        "Death and Decay: environmental hazard.",
        "Acherus approves this desecration.",
        "The reaper marks his passage.",
        "This space is now unfit for life.",
        "The endless winter kills the grass.",
        "Acherus blights the ground.",
        "The scourge claims the earth.",
        "I have poisoned this place.",
        "Death covers the ground like frost.",
        "The void leaves nothing alive.",
        "Acherus decrees: this space is death.",
        "The reaper's mark is permanent.",
        "I have made this ground unholy.",
        "The endless winter rules here.",
        "Acherus sustains the decay.",
        "The scourge's corruption spreads.",
        "The floor remembers death now.",
      },
    },

    -- Summons / Big moments
    {
      id = "dk_raise_dead",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellID = 46584 },
      messages = {
        "Raise Dead. Team meeting, attendance required.",
        "Skeleton assistant deployed.",
        "I brought a friend. They are mostly compliant.",
        "Necromancy: the original networking.",
        "If Midnight gets weird, I get weirder.",
        "Minion online. Please ignore the smell.",
        "Who needs friends when you have the unquiet dead.",
        "Workforce expanded via questionable ethics.",
        "The corpse rises at my command.",
        "Acherus gifts me an undead servant.",
        "The scourge animates the fallen.",
        "A skeleton joins the cause.",
        "Death gives up another servant.",
        "The void fills the empty corpse.",
        "Acherus says: rise and serve.",
        "An undead minion obeys now.",
        "I have requisitioned the dead.",
        "The endless winter compels undeath.",
        "Acherus blesses this new servant.",
        "The reaper's servant answers the call.",
        "A corpse shambles to attention.",
        "Death commands. The dead obey.",
        "The scourge has many servants.",
        "I have made a friend from bones.",
        "Acherus provides minions freely.",
        "The void animates what was still.",
        "A new skeleton enters service.",
        "The endless winter gives undeath.",
        "Acherus approves this resurrection.",
        "The reaper's grip raises the dead.",
        "I am never alone. Death ensures it.",
        "A corpse walks at my side now.",
        "The scourge's workforce: infinite.",
        "Acherus provides the faithful with help.",
        "The void breathes life into bones.",
        "A skeletal assistant reports for duty.",
        "Death has provided a new tool.",
        "The endless winter animates corpses.",
        "Acherus makes no waste of bodies.",
        "The reaper's army grows.",
        "Welcome to the undead collective.",
      },
    },
    {
      id = "dk_army_of_the_dead",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 180,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellID = 42650 },
      messages = {
        "Army of the Dead. I have brought backups.",
        "This is now a group project.",
        "Acherus HR has approved mass hiring.",
        "If the Sunwell goes dark, I'm bringing my own crowd.",
        "Welcome to the apocalypse, population: me.",
        "Undead union meeting. We are all invited.",
        "The battlefield just became very crowded.",
        "My solution involves more skeletons.",
        "The earth trembles with undead.",
        "Acherus has unleashed his army.",
        "The scourge's endless forces arrive.",
        "A multitude of corpses rise at once.",
        "Death brings an entire infantry.",
        "The void fills thousands of bodies.",
        "Acherus says: I bring legions.",
        "An undead battalion answers the call.",
        "I have summoned the eternal horde.",
        "The endless winter covers the earth.",
        "Acherus provides overwhelming force.",
        "The reaper's army: unlimited.",
        "A sea of skeletons surrounds us.",
        "Death has assembled an empire.",
        "The scourge's hosts are numberless.",
        "I am surrounded by the undead faithful.",
        "Acherus: the greatest necromancer.",
        "The void births an endless tide.",
        "The army of the dead is manifest.",
        "The endless winter claims all.",
        "Acherus feeds on this victory.",
        "The reaper's harvest: complete.",
        "We are legion. We are death.",
        "The bones of ages rise at once.",
        "The scourge's true power: revealed.",
        "Acherus walks among his army.",
        "The void: infinite and terrible.",
        "Death's military service has begun.",
        "The endless winter reigns eternal.",
        "Acherus: supreme warlord.",
        "The reaper's forces: overwhelming.",
        "Behold: the undead apocalypse.",
      },
    },
    {
      id = "dk_dark_transformation",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellID = 63560 },
      messages = {
        "Dark Transformation. Minion upgrade applied.",
        "Glow-up, but make it necrotic.",
        "Ghoul mode: deluxe edition.",
        "I pressed the button and the vibes got worse.",
        "Midnight can keep its shadows. I make my own.",
        "Enhancement complete. Please fear responsibly.",
        "My pet is now a bigger problem.",
        "Powering up the nightmare assistant.",
        "The minion undergoes dark metamorphosis.",
        "Acherus elevates my servant.",
        "The scourge's blessing: empowerment.",
        "My ghoul becomes a terror.",
        "Death magic surges through my minion.",
        "The void transforms. Strength increases.",
        "Acherus says: be strong and terrible.",
        "An upgraded nightmare awakens.",
        "I have made my servant legendary.",
        "The endless winter empowers the faithful.",
        "Acherus enhances what he has created.",
        "The reaper's gift: unstoppable power.",
        "My ghoul is now a demon.",
        "Death magic boils in its veins.",
        "The scourge transforms weakness to strength.",
        "I have made a better monster.",
        "Acherus delights in this transformation.",
        "The void grants terrible power.",
        "The transformation is complete.",
        "The endless winter makes all stronger.",
        "Acherus blesses the evolved.",
        "The reaper's power concentrated.",
        "My minion: fear incarnate now.",
        "The bones burn with dark fire.",
        "The scourge's upgrade: maximum.",
        "Acherus approves this enhancement.",
        "The void pours through every limb.",
        "Death magic reaches peak intensity.",
        "The endless winter burns within.",
        "Acherus has made a masterpiece.",
        "The reaper's work is beautiful.",
        "Behold: transcendent nightmare.",
      },
    },
    {
      id = "dk_summon_gargoyle",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 90,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellID = 49206 },
      messages = {
        "Summon Gargoyle. Air support is undead now.",
        "Look up. Bad news has wings.",
        "I have called in a flying lawsuit.",
        "Gargoyle deployed. Please panic politely.",
        "If the Void is in the sky, so is my gargoyle.",
        "Acherus delivers. Same-day shipping.",
        "My pet has taken the high ground.",
        "The atmosphere is now hostile.",
        "The stone sentinel takes flight.",
        "Acherus sends an aerial nightmare.",
        "The scourge's watcher has arrived.",
        "A gargoyle descends from death itself.",
        "The void births a flying reaper.",
        "Wings of stone beat overhead.",
        "Acherus says: I bring judgment from above.",
        "An undead sentinel patrols the sky.",
        "I have summoned a monster of stone.",
        "The endless winter flies on ancient wings.",
        "Acherus provides aerial superiority.",
        "The reaper's eye from above.",
        "A stone guardian circles us.",
        "Death flies. The gargoyle descends.",
        "The scourge reclaims the sky.",
        "I am no longer alone in battle.",
        "Acherus never leaves his servants alone.",
        "The void takes wing and hunts.",
        "The gargoyle: sentinel of death.",
        "The endless winter watches from above.",
        "Acherus approves this aerial addition.",
        "The reaper's representative: arrived.",
        "We have air support now.",
        "The stones come alive in undeath.",
        "The scourge's defenses: complete.",
        "Acherus has sent reinforcement.",
        "The void manifests in stone.",
        "Death watches from the sky.",
        "The endless winter soars.",
        "Acherus walks beside me always.",
        "The reaper's garrison: fortified.",
        "Behold: the undead sky guardian.",
      },
    },

    -- Frost identity
    {
      id = "dk_pillar_of_frost",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellID = 51271 },
      messages = {
        "Pillar of Frost. I have become a winter thesis.",
        "Strength increased. Chill increased.",
        "I am now legally colder.",
        "Power spike: frosty edition.",
        "If Midnight brings darkness, I bring a blizzard attitude.",
        "The cold has arrived with paperwork.",
        "I am standing taller. Mostly out of spite.",
        "Frost pillar up. Feel free to regret it.",
        "The ice crystallizes around me.",
        "I stand empowered by winter itself.",
        "Acherus strengthens the frost-touched.",
        "The scourge grants its favor.",
        "My body becomes a conduit of glacial power.",
        "The void amplifies my strength.",
        "Acherus says: rise tall and cold.",
        "A pillar of frost forms around me.",
        "I have become harder, colder, stronger.",
        "The endless winter flows through me.",
        "Acherus empowers the devoted.",
        "The reaper's might cascades.",
        "I am a monument to winter.",
        "Death's strength fills me completely.",
        "The scourge's power is mine.",
        "I am a beacon of frost.",
        "Acherus blesses strength and chill.",
        "The void magnifies my presence.",
        "The pillar forms. The power rises.",
        "The endless winter empowers utterly.",
        "Acherus elevates his devoted.",
        "The reaper's blessing: supreme might.",
        "I stand as death incarnate.",
        "The frost claims dominion.",
        "The scourge's apex: me.",
        "Acherus approves this display.",
        "The void feeds my strength.",
        "Death makes me powerful.",
        "The endless winter surrounds and empowers.",
        "Acherus watches his masterpiece.",
        "The reaper's chosen: blessed.",
        "Behold: a monument to death.",
      },
    },

    -- Blood identity
    {
      id = "dk_dancing_rune_weapon",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellID = 49028 },
      messages = {
        "Dancing Rune Weapon. I brought a plus-one.",
        "My weapon is now doing interpretive violence.",
        "Double the blade, double the problems.",
        "Runes are humming. Someone is about to have a bad time.",
        "If Midnight is full of shadows, I brought extra steel.",
        "Mirror match: me vs you. Spoiler: me.",
        "This is my weapon performing modern art.",
        "The runeblade has learned choreography.",
        "The weapon animates with death magic.",
        "Acherus grants a phantom blade.",
        "The scourge multiplies my steel.",
        "A ghostly runeblade appears.",
        "Death wields itself through magic.",
        "The void creates an echo-blade.",
        "Acherus says: two is better than one.",
        "A mirrored weapon dances beside me.",
        "I have doubled my martial prowess.",
        "The endless winter sharpens both blades.",
        "Acherus grants a spectral companion.",
        "The reaper multiplies his strike.",
        "Two runes sing in unison.",
        "Death fights beside me now.",
        "The scourge's power: duplicated.",
        "I am no longer alone in combat.",
        "Acherus provides a phantom soldier.",
        "The void births a mirror-self.",
        "The weapon dances with purpose.",
        "The endless winter strikes twice now.",
        "Acherus approves this duplication.",
        "The reaper's reach: doubled.",
        "We are synchronized violence.",
        "The runes sing in perfect harmony.",
        "The scourge's assault: unified.",
        "Acherus has made me twice the threat.",
        "The void dances with me.",
        "Death mirrors my every move.",
        "The endless winter multiplies our power.",
        "Acherus watches his blades dance.",
        "The reaper's choreography: flawless.",
        "Behold: the duality of death.",
      },
    },

    -- Mobility
    {
      id = "dk_wraith_walk",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      conditions = { class = "DEATHKNIGHT", unit = "player", spellID = 212552 },
      messages = {
        "Wraith Walk. I am speed, but make it haunted.",
        "Ghosting this situation, literally.",
        "I am leaving. The floor cannot stop me.",
        "Phase through problems. Return later with violence.",
        "If Midnight gets spooky, I get spookier.",
        "I have become a fast nightmare.",
        "Wraith Walk engaged. Do not perceive me.",
        "Excuse me. I am becoming intangible.",
        "The void carries me swiftly.",
        "I become one with death's essence.",
        "Acherus speeds his servant forward.",
        "The scourge propels the faithful.",
        "I am now a wraith of speed.",
        "The void phases through obstacles.",
        "Acherus says: move with the wind.",
        "A ghostly form speeds away.",
        "I have transcended earthly movement.",
        "The endless winter carries me far.",
        "Acherus blesses speed and stealth.",
        "The reaper moves as shadows move.",
        "My form becomes spectral and swift.",
        "Death travels faster than thought.",
        "The scourge: too fast to follow.",
        "I am a phantom in motion.",
        "Acherus grants supernatural speed.",
        "The void whisks me away.",
        "The wraith walk commences.",
        "The endless winter provides wings.",
        "Acherus approves this escape.",
        "The reaper cannot be caught.",
        "We move through space itself.",
        "The void bends around us.",
        "The scourge's speed: unmatched.",
        "Acherus ensures our safe passage.",
        "The endless winter slides us forward.",
        "Death knows no obstacles.",
        "The scourge glides like a phantom.",
        "Acherus watches us vanish.",
        "The reaper's speed: legendary.",
        "Behold: the ghost that was me.",
      },
    },

    -- Spec change (non-spell, DK flavored)
    {
      id = "dk_spec_changed",
      event = "PLAYER_SPECIALIZATION_CHANGED",
      cooldown = 10,
      conditions = { class = "DEATHKNIGHT" },
      messages = {
        "Spec shift detected: <spec>. Adjust your expectations.",
        "<spec> mode. The runes feel different.",
        "Acherus approves this new mood: <spec>.",
        "Switched to <spec>. The violence has been rescheduled.",
        "<spec> selected. Please file complaints with the Ebon Blade.",
        "The death knight transforms: <spec>.",
        "My power shifts. <spec> is my path now.",
        "Acherus teaches a new way: <spec>.",
        "The scourge's tactics evolve: <spec>.",
        "Runes hum with <spec> purpose.",
        "I embrace the <spec> identity.",
        "Death takes many forms. Now: <spec>.",
        "The void reshapes my power: <spec>.",
        "Acherus accepts my new <spec> form.",
        "The cold adapts. <spec> rises.",
        "I am reborn in <spec> glory.",
        "The endless winter chooses: <spec>.",
        "Acherus whispers: <spec> is your destiny.",
        "The reaper shifts: <spec> mode.",
        "<spec>: the voice of death now.",
        "My runes sing in <spec> harmony.",
        "The scourge flows as <spec> demands.",
        "I am now <spec> incarnate.",
        "Acherus empowers the <spec> path.",
        "The void reshapes for <spec>.",
        "Death wears many faces. Today: <spec>.",
        "The endless winter teaches <spec>.",
        "Acherus guides <spec> mastery.",
        "The reaper's chosen form: <spec>.",
        "We adapt. <spec> is our new strength.",
        "The void recognizes <spec>.",
        "The scourge flows as <spec>.",
        "Acherus blesses this <spec> moment.",
        "The endless winter supports <spec>.",
        "Death manifests as <spec>.",
        "The scourge becomes <spec>.",
        "Acherus watches <spec> unfold.",
        "The reaper's <spec>: perfected.",
        "<spec>: the shape of our power.",
        "The void embraces <spec>.",
      },
    },

    -- ====================================================================
    -- BLOOD DEATH KNIGHT SPEC-SPECIFIC TRIGGERS (SpecID: 250)
    -- ====================================================================
    {
      id = "dk_heart_strike",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 12,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 250, spellName = "Heart Strike" },
      messages = {
        "Heart Strike. Targeting vital organs with enthusiasm.",
        "Striking the heart. Metaphorically and literally.",
        "Heart Strike deployed. Cardiology, but hostile.",
        "I have opinions about your circulatory system.",
        "The heart is the problem. I am the solution.",
        "Precision violence, organ-specific.",
        "The blood knight strikes true.",
        "Your vital system just became my target.",
        "Acherus teaches anatomy through violence.",
        "The scourge's healing magic: punching hearts.",
        "I strike where life itself flows.",
        "The void demands the organ's surrender.",
        "Acherus says: seize the heart.",
        "A warrior's strike, precision-honed.",
        "I have learned cardiology from death.",
        "The endless winter chills the heart.",
        "Acherus blesses the blood knight.",
        "The reaper's favorite target: your heart.",
        "Heart tissue: about to receive my attention.",
        "Death knows where life pools.",
        "The scourge: heart specialist.",
        "I strike with surgical precision.",
        "Acherus gifts healing through harm.",
        "The void flows where blood flows.",
        "Your pulse: my target now.",
        "The endless winter strikes center.",
        "Acherus approves this vital attack.",
        "The reaper's touch finds the core.",
        "We are blood knights. This is our art.",
        "The heart is weakness. I exploit it.",
        "The scourge feeds on vital fluids.",
        "Acherus teaches: all life flows.",
        "The endless winter focuses on center.",
        "Death knows the anatomy of life.",
        "The scourge penetrates to the core.",
        "Acherus watches the blood knight rise.",
        "The reaper's precision: unmatched.",
        "This strike nourishes the devoted.",
        "The blood flows. We feast.",
        "Acherus smiles at our mastery.",
      },
    },
    {
      id = "dk_blood_boil",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 10,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 250, spellName = "Blood Boil" },
      messages = {
        "Blood Boil. Literally boiling blood.",
        "Your blood pressure just became my problem.",
        "Boiling blood. Not medically advisable.",
        "Internal temperature: rising. Prognosis: poor.",
        "If your blood was calm, it is not anymore.",
        "Blood Boil engaged. Biology regrets this.",
      },
    },
    {
      id = "dk_marrowrend",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 10,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 250, spellName = "Marrowrend" },
      messages = {
        "Marrowrend. Rending marrow. It's in the name.",
        "Bone deep regrets incoming.",
        "Your skeleton has filed a complaint.",
        "Marrow extracted. Aggressively.",
        "Structural integrity: compromised.",
        "I am going after the bones now.",
      },
    },
    {
      id = "dk_bonestorm",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      category = "cooldowns",
      conditions = { class = "DEATHKNIGHT", specID = 250, spellName = "Bonestorm" },
      messages = {
        "Bonestorm. Skeleton tornado deployed.",
        "I have become a whirlwind of regret and calcium.",
        "Bonestorm engaged. Please admire the structural damage.",
        "Spinning bones. For health reasons.",
        "If Midnight wanted intact skeletons, too late.",
        "Hurricane of bone. Very metal.",
      },
    },
    {
      id = "dk_vampiric_blood",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      category = "defensive",
      conditions = { class = "DEATHKNIGHT", specID = 250, spellName = "Vampiric Blood" },
      messages = {
        "Vampiric Blood. I am temporarily more immortal.",
        "Blood thirst: maximum. Survival: ensured.",
        "Vampiric mode engaged. The count approves.",
        "My blood now has aggressive opinions.",
        "Vampiric sustain online. Death is optional.",
        "Blood magic: the self-care edition.",
      },
    },
    {
      id = "dk_blood_tap",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "utility",
      conditions = { class = "DEATHKNIGHT", specID = 250, spellName = "Blood Tap" },
      messages = {
        "Blood Tap. Borrowing runes from my veins.",
        "Tapping into the crimson reservoir.",
        "Blood donation, but to myself.",
        "Rune economy: blood-based.",
        "Self-banking via bloodstream.",
      },
    },
    {
      id = "dk_consumption",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 250, spellName = "Consumption" },
      messages = {
        "Consumption. Healing through violence.",
        "Consuming health. Via attack.",
        "Life drain: aggressive edition.",
        "If I hit you, I heal me. Economics.",
        "Consumption online. Your HP is mine.",
      },
    },

    -- ====================================================================
    -- FROST DEATH KNIGHT SPEC-SPECIFIC TRIGGERS (SpecID: 251)
    -- ====================================================================
    {
      id = "dk_obliterate",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 12,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 251, spellID = 49020 },
      messages = {
        "Obliterate. The name is self-explanatory.",
        "Obliterating with two weapons. Efficiency.",
        "Obliteration protocol: yes.",
        "Dual wield deletion engaged.",
        "If it existed, past tense.",
        "Two blades, one target, zero survivors.",
      },
    },
    {
      id = "dk_frost_strike",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 251, spellID = 49143 },
      messages = {
        "Frost Strike. Cold and calculated.",
        "Striking with winter's approval.",
        "Frost Strike deployed. Temperature: hostile.",
        "The cold never bothered me. You, however.",
        "Icy violence engaged.",
        "Strike from the frozen north.",
      },
    },
    {
      id = "dk_howling_blast",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 12,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 251, spellID = 49184 },
      messages = {
        "Howling Blast. AoE winter deployed.",
        "Blasting with audible cold.",
        "The wind howls. So does the damage.",
        "Howling Blast online. Volume: loud. Temperature: no.",
        "If you wanted warmth, wrong death knight.",
        "Frost AoE with sound effects.",
      },
    },
    {
      id = "dk_remorseless_winter",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 251, spellID = 196770 },
      messages = {
        "Remorseless Winter. Winter without regret.",
        "Deploying a blizzard with attitude.",
        "The cold is here. Remorse is not.",
        "Winter aura: merciless edition.",
        "If Midnight brought darkness, I brought frostbite.",
        "Remorseless and frozen. My brand.",
      },
    },
    {
      id = "dk_empower_rune_weapon",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { class = "DEATHKNIGHT", specID = 251, spellID = 47568 },
      messages = {
        "Empower Rune Weapon. Instant runes deployed.",
        "Rune battery fully charged.",
        "Empowerment complete. The spam begins.",
        "Runes refreshed. Please stand back.",
        "If you wanted a break, denied.",
        "Power surge via runic overdrive.",
      },
    },
    {
      id = "dk_breath_of_sindragosa",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { class = "DEATHKNIGHT", specID = 251, spellID = 152279 },
      messages = {
        "Breath of Sindragosa. Channeling dragon winter.",
        "Sindragosa approved this breath attack.",
        "Dragon breath: frost edition.",
        "If Midnight wanted warmth, I brought the Frost Queen.",
        "Breath of the damned dragon engaged.",
        "Sindragosa says: freeze.",
      },
    },
    {
      id = "dk_frostwyrms_fury",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 90,
      category = "cooldowns",
      conditions = { class = "DEATHKNIGHT", specID = 251, spellID = 279302 },
      messages = {
        "Frostwyrm's Fury. Summoning undead dragon rage.",
        "Frostwyrm deployed. The sky is now hostile.",
        "Dragon fury: frost zombie edition.",
        "If Midnight flies, the wyrm objects.",
        "Frostwyrm online. Panic politely.",
        "Undead dragon fury engaged. Run.",
      },
    },

    -- ====================================================================
    -- UNHOLY DEATH KNIGHT SPEC-SPECIFIC TRIGGERS (SpecID: 252)
    -- ====================================================================
    {
      id = "dk_scourge_strike",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 12,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 252, spellID = 55090 },
      messages = {
        "Scourge Strike. Plague delivery system.",
        "Striking with infectious enthusiasm.",
        "Scourge deployed. Health inspector not invited.",
        "Disease transmission: weaponized.",
        "If you wanted hygiene, wrong death knight.",
        "Plague strike with commitment.",
      },
    },
    {
      id = "dk_festering_strike",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 10,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 252, spellID = 85948 },
      messages = {
        "Festering Strike. Wounds festering on demand.",
        "Infection multiplication protocol.",
        "Festering engaged. Antibiotics not included.",
        "Your wounds have developed opinions.",
        "Medical condition: worsening. By design.",
        "Festering wounds deployed. Please do not lance.",
      },
    },
    {
      id = "dk_apocalypse",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 45,
      category = "cooldowns",
      conditions = { class = "DEATHKNIGHT", specID = 252, spellID = 275699 },
      messages = {
        "Apocalypse. End times on demand.",
        "Deploying the apocalypse. Locally.",
        "Apocalypse engaged. The horsemen approve.",
        "If Midnight wanted subtle, I brought Revelation.",
        "End of days protocol: activated.",
        "Apocalypse now. File your complaints in writing.",
      },
    },
    {
      id = "dk_outbreak",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 252, spellID = 77575 },
      messages = {
        "Outbreak. Spreading diseases professionally.",
        "Plague distribution: initiated.",
        "Outbreak online. Please do not report to health authorities.",
        "If you wanted wellness, wrong class.",
        "Disease outbreak deployed. Quarantine optional.",
        "Infection control: abandoned.",
      },
    },
    {
      id = "dk_epidemic",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 15,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 252, spellID = 207317 },
      messages = {
        "Epidemic. Plague AoE deployed.",
        "Disease spreads. By design.",
        "Epidemic engaged. Social distancing: irrelevant.",
        "If one plague is good, area plague is better.",
        "Infection radius: expanded.",
        "Epidemic protocol: active.",
      },
    },
    {
      id = "dk_unholy_blight",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "cooldowns",
      conditions = { class = "DEATHKNIGHT", specID = 252, spellID = 115989 },
      messages = {
        "Unholy Blight. Mass infection deployed.",
        "Blight engaged. Everyone gets sick.",
        "Unholy contamination protocol.",
        "If Midnight wanted health, I brought blight.",
        "Area plague: activated.",
        "Blight online. Please panic responsibly.",
      },
    },
    {
      id = "dk_soul_reaper",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 20,
      category = "rotation",
      conditions = { class = "DEATHKNIGHT", specID = 252, spellName = "Soul Reaper" },
      messages = {
        "Soul Reaper. Executing with soul theft.",
        "Reaping souls. It's a living. Sort of.",
        "Soul Reaper deployed. Your soul: harvested.",
        "If HP is low, soul collection begins.",
        "Reaping protocol: active.",
        "Soul harvest engaged.",
      },
    },
    {
      id = "dk_abomination_limb",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "cooldowns",
      conditions = { class = "DEATHKNIGHT", specID = 252, spellID = 315443 },
      messages = {
        "Abomination Limb. Summoning questionable anatomy.",
        "Giant arm deployed. Do not ask where from.",
        "Abomination limb online. Biology has filed a complaint.",
        "If Midnight wanted normal, I brought body horror.",
        "Limb of dubious origin: active.",
        "Abomination protocols engaged. Do not perceive closely.",
      },
    },
  },
})
