-- EmoteControl - Void Elf Race Pack

local _, EC = ...

if not EC or type(EC.RegisterPack) ~= "function" then
  return
end

EC:RegisterPack({
  id = "race_voidelf",
  name = "Void Elf Race Pack",
  defaults = { race = "VOIDELF" },
  triggers = {
    -- Combat start
    {
      id = "voidelf_combat_start",
      event = "PLAYER_REGEN_DISABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "channels the Void, shadows coiling around them.",
        "embraces the darkness within, ready to fight.",
        "enters combat, void energy crackling.",
        "prepares to unleash the power of the Rift.",
        "stands ready, touched by the Void.",
        "lets void whispers guide their strikes.",
        "enters battle, shadows answering their call.",
        "draws upon the abyss, power surging within.",
        "invokes the eldritch forces, eyes glowing purple.",
        "tears through the veil of reality, ready for battle.",
        "summons void tentacles of arcane energy.",
        "becomes one with the darkness itself.",
        "the Void hungers, and they answer the call.",
        "manifests spatial distortions around their form.",
        "calls out to the Rift, answering with void energy.",
        "taps into forbidden knowledge, shadows expanding.",
        "feels the whispers strengthen, combat imminent.",
        "becomes a conduit for eldritch power.",
        "the fabric of space warps around them.",
        "void tendrils unfurl, seeking combat.",
        "reaches into the abyss for power.",
        "the whispers crescendo into a battle cry.",
        "shadow magic coalesces into a devastating aura.",
        "steps forward, the Rift crackling at their fingertips.",
        "embraces the void-touched darkness within their bloodline.",
        "feels reality bending to their will.",
        "summons the hunger of the void itself.",
        "the area grows cold as void energy manifests.",
        "stands defiant, void power radiating outward.",
        "whispers ancient Void-words in challenge.",
        "pulls more power from the Rift with each breath.",
        "transforms, becoming something other.",
        "the Void sings through them, eager for conflict.",
        "readies themselves, the whispers howling.",
        "void-touched and dangerous, they advance.",
        "the space around them becomes unstable and dark.",
        "their eyes flash with eldritch void-sight.",
        "the whispers drown out all else as combat begins.",
        "they step into the shadows, fully embracing their nature.",
        "void energy crackles across their skin like lightning.",
        "the boundary between worlds grows thin.",
        "they are ready, utterly void-touched and deadly.",
      },
    },

    -- Combat end
    {
      id = "voidelf_combat_end",
      event = "PLAYER_REGEN_ENABLED",
      cooldown = 45,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "releases the Void, shadows dissipating.",
        "stands victorious, void whispers fading.",
        "relaxes, the darkness receding.",
        "calms, having mastered the Void once more.",
        "exhales, void energy settling.",
        "silences the whispers, control maintained.",
        "stands tall, void power contained.",
        "seals the rift, the battle concluded.",
        "the void whispers grow distant, satisfied.",
        "sheathe their eldritch power, order restored.",
        "the purple glow in their eyes dims gradually.",
        "void tendrils dissipate into nothingness.",
        "the fabric of space returns to normal.",
        "they catch their breath, the abyss satisfied.",
        "the hunger of the Void sated for now.",
        "void-touched and weary, they rest.",
        "the whispers fade to comfortable silence.",
        "shadow magic ebbs away from their form.",
        "they regain their composure, humanity returning.",
        "the connection to the Rift weakens.",
        "peace settles over them once more.",
        "void energy dissipates into the ethereal.",
        "the eldritch glow fades from their presence.",
        "they ground themselves in the material plane.",
        "the abyss releases its hold.",
        "shadows retreat, their purpose fulfilled.",
        "the Rift's pull diminishes.",
        "void-touched calm settles upon them.",
        "they slowly return to their true form.",
        "the whispered victory echoes fade.",
        "control reasserts itself, darkness submissive.",
        "they stand alone again, void appeased.",
        "spatial distortions collapse harmlessly.",
        "the void-hunger rests, temporarily satiated.",
        "balance between light and shadow restored.",
        "the ethereal bonds strengthen as void weakens.",
        "the whispers murmur gentle satisfaction.",
        "they emerge, still touched but contained.",
        "the abyss grows quiet, at least for now.",
        "void-touched strength subsides to manageable levels.",
        "they settle into themselves, the darkness dormant.",
      },
    },

    -- Death
    {
      id = "voidelf_death",
      event = "PLAYER_DEAD",
      cooldown = 0,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "falls, consumed by the Void.",
        "collapses, void energy scattering.",
        "succumbs, the whispers overwhelming.",
        "falls to darkness.",
        "dissolves into shadow.",
        "the abyss claims them, at least for now.",
        "void-touched resilience finally broken.",
        "the whispers drag them down into oblivion.",
        "they fade, becoming one with the Void.",
        "eldritch forces consume their mortal form.",
        "the Rift opens wide, pulling them through.",
        "void tendrils wrap around them, victorious.",
        "the whispers sing a song of passing.",
        "their void-touched form shatters.",
        "they slip between worlds, lost to darkness.",
        "the void hunger grows as they fall.",
        "shadows overwhelm their last defense.",
        "the whispers achieve their dark purpose.",
        "reality fragments as they collapse.",
        "the Void takes what the Void desires.",
        "they succumb to eldritch hunger.",
        "void energy tears through them.",
        "the abyss opens beneath their feet.",
        "whispers become screams as they fall.",
        "the space around them collapses inward.",
        "void-touched, but not void-protected.",
        "the Rift claims them temporarily.",
        "shadow consumes light within them.",
        "they descend into the whispers' embrace.",
        "the void-hunger grows, satisfied momentarily.",
        "their connection to reality severs.",
        "the whispers feast upon their fall.",
        "void energy dissipates with their defeat.",
        "the abyss swallows them whole.",
        "eldritch powers overwhelm their defenses.",
        "they tumble through spatial rifts.",
        "the void-touched cannot escape fate.",
        "whispers of ancient Void-speech echo their passing.",
        "they become shadow, at least briefly.",
        "the Void hungers, and hunger is satisfied.",
      },
    },

    -- Resurrection
    {
      id = "voidelf_alive",
      event = "PLAYER_ALIVE",
      cooldown = 0,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "returns from the Void, shadows reforming.",
        "rises again, void-touched resilience.",
        "stands once more, the Rift endures.",
        "returns, void energy restored.",
        "reforms from shadow, unbroken.",
        "the abyss releases them, their purpose unfulfilled.",
        "void-touched persistence brings them back.",
        "whispers call them back from oblivion.",
        "they reform, the Void incomplete in its claim.",
        "eldritch bonds pull them back to life.",
        "the Rift spits them out, unsatisfied.",
        "void tendrils reweave their form.",
        "the whispers grant them another chance.",
        "they rise, their void-touched nature unbroken.",
        "they emerge from shadow once more.",
        "the void-hunger waits, denied this time.",
        "shadows coalesce, pulling them back.",
        "the whispers refuse to release them.",
        "reality knits them together again.",
        "the Void spins them back to the living.",
        "they claw their way back to existence.",
        "eldritch resilience keeps them alive.",
        "void energy reconstructs their form.",
        "the abyss cannot hold them permanently.",
        "whispers welcome them back to the material.",
        "they return, the Rift's hold weakening.",
        "void-touched and defiant, they stand again.",
        "shadows cannot keep what the Void marks.",
        "the whispers guided them home.",
        "they slip back through the veil.",
        "void energy blazes through them once more.",
        "the connection to the Rift restored.",
        "eldritch power suffuses their renewed form.",
        "the abyss admits temporary defeat.",
        "whispers sing their return to life.",
        "they rise with void-touched determination.",
        "the Rift spits them back defiantly.",
        "void-touched, resilient, and reborn.",
        "they emerge stronger from the darkness.",
        "the whispers approve of their return.",
      },
    },

    -- Spatial Rift (racial ability)
    {
      id = "spatial_rift",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 30,
      category = "utility",
      conditions = { spellID = 256948 },
      messages = {
        "Spatial Rift. Tearing through reality.",
        "Opening a rift. Physics are optional.",
        "Void portal deployed. Quick escape ready.",
        "Rift created. The Void provides shortcuts.",
        "Space has been compromised.",
        "Reality? More like suggestion.",
        "Rift online. Teleport pending.",
        "Ripping through the fabric of existence.",
        "The abyss opens a path forward.",
        "Folding space like paper with eldritch precision.",
        "Void-touched fingers trace dimensional boundaries.",
        "A whisper tears the world in two.",
        "The barrier between here and there becomes thin.",
        "Spatial distortion activated. Escape vector prepared.",
        "The Rift answers, opening a shortcut.",
        "Stepping sideways through reality itself.",
        "The void hungers to transport me elsewhere.",
        "A portal of shadow and spatial magic.",
        "Warping space with void-touched ease.",
        "The material plane yields to eldritch will.",
        "Opening a shortcut through the abyss.",
        "The Rift's gift: freedom from distance.",
        "Stepping into shadow, emerging anew.",
        "A tear in the world serves as passage.",
        "The whispers guide through alternate paths.",
        "Void energy bends space to my whim.",
        "A rift opens, the Void calls me elsewhere.",
        "Spatial dimensions realign for quick escape.",
        "The fabric of reality trembles and gives way.",
        "Eldritch teleportation engaged.",
        "The Rift provides passage between worlds.",
        "Space collapses and reforms around me.",
        "A void portal, swift as thought.",
        "The abyss opens a road of shadows.",
        "Reality bends to accommodate my departure.",
        "Void-touched speed through dimensional rifts.",
        "The whispers sing of distant arrival.",
        "A shortcut carved through the darkness itself.",
        "The barrier between places becomes negotiable.",
        "Stepping through the veil of worlds.",
      },
    },

    -- Void-themed flavor
    {
      id = "voidelf_whispers",
      event = "ZONE_CHANGED_NEW_AREA",
      cooldown = 120,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "pauses, hearing void whispers in this place.",
        "senses the Void's presence here.",
        "feels shadow energies swirling nearby.",
        "hears echoes from the Rift.",
        "listens as the Void murmurs in the distance.",
        "the whispers grow louder in unfamiliar lands.",
        "void-touched senses tingle with ancient power.",
        "they can feel the abyss closer here.",
        "eldritch whispers speak of this place.",
        "the Rift's presence grows stronger.",
        "shadow magic saturates this area.",
        "the whispers seem familiar, yet alien.",
        "void-touched awareness expands in this place.",
        "the abyss sings in this location.",
        "they sense something otherworldly nearby.",
        "the whispers grow excited about new surroundings.",
        "spatial anomalies hint at Void influence.",
        "the air feels thick with void-touched essence.",
        "the Rift seems particularly close here.",
        "ancient whispers resonate through this zone.",
        "void energy crackles at the edges of perception.",
        "the darkness here speaks in familiar tongues.",
        "they can taste the Void in the air.",
        "eldritch presences acknowledge their arrival.",
        "the whispers welcome them to this realm.",
        "shadow-touched grounds feel like home.",
        "the abyss opens its awareness to them.",
        "void tendrils brush against their consciousness.",
        "the whispers grow almost companionable here.",
        "spatial distortions mark this place as special.",
        "they feel the Rift's attention turn their way.",
        "the void-hunger seems more at peace here.",
        "ancient void-touched magic permeates the area.",
        "the whispers speak of secrets in this land.",
        "shadow magic runs deep in this zone.",
        "the Void seems almost inviting here.",
        "eldritch forces swirl around them invisibly.",
        "the whispers crescendo with recognition.",
        "void-touched essence flows through this place.",
        "the abyss acknowledges a kindred location.",
      },
    },

    {
      id = "voidelf_magic",
      event = "UNIT_SPELLCAST_SUCCEEDED",
      cooldown = 60,
      category = "flavor",
      channel = "EMOTE",
      conditions = { spellName = { "Portal:*", "Teleport:*" }, randomChance = 0.4 },
      messages = {
        "weaves void energy into the portal.",
        "channels shadows alongside arcane power.",
        "bends space with void-touched magic.",
        "calls upon the Rift to aid their spell.",
        "threads shadow into the portal's arcane weave.",
        "merges eldritch power with arcane knowledge.",
        "the abyss itself strengthens the spell.",
        "void whispers amplify the magical energies.",
        "shadows coalesce within the portal framework.",
        "spatial magic bends to void-touched will.",
        "the Rift's power flows through the arcane.",
        "eldritch tendrils wrap around the spell.",
        "void-touched resonance strengthens the portal.",
        "the whispers sing the spell into being.",
        "abyss-touched magic crackles with power.",
        "void energy crystallizes within the spell.",
        "the Rift adds its ancient strength.",
        "shadow and arcane merge into something new.",
        "eldritch forces dance through the arcane.",
        "void-touched fingers trace spell patterns.",
        "the whispers guide the magical energies.",
        "spatial distortions enhance the spell's reach.",
        "the abyss lends weight to the incantation.",
        "void-touched magic pulses with otherworldly power.",
        "the Rift resonates with the spell's frequency.",
        "eldritch geometry stabilizes the portal.",
        "void whispers weave through every word.",
        "shadow-touched knowledge enhances the spell.",
        "the abyss thrums with anticipation.",
        "void energy crackles at spell completion.",
        "the whispers achieve their magical purpose.",
        "spatial magic and void essence intertwine.",
        "eldritch power floods through the arcane.",
        "the Rift opens to strengthen the portal.",
        "void-touched essence imprints upon the spell.",
        "the whispers celebrate the spell's completion.",
        "abyss-touched magic reaches its crescendo.",
        "void tendrils stabilize the dimensional gateway.",
        "the Rift smiles, satisfied with their magic.",
        "eldritch forces ensure the spell's success.",
      },
    },

    {
      id = "voidelf_achievement",
      event = "ACHIEVEMENT_EARNED",
      cooldown = 60,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "celebrates, void energy flickering with excitement.",
        "smiles, the Void approves of this achievement.",
        "nods proudly, mastery recognized.",
        "stands tall, void whispers pleased.",
        "accepts this honor, shadows curling in approval.",
        "the abyss sings approval of their success.",
        "void-touched resilience rewarded and recognized.",
        "the whispers cheer for their accomplishment.",
        "eldritch forces celebrate their achievement.",
        "the Rift acknowledges their growing power.",
        "void energy pulses with pride.",
        "the whispers grow content with their victory.",
        "shadow magic swirls in celebration.",
        "void-touched determination has borne fruit.",
        "the abyss rumbles its satisfaction.",
        "eldritch powers recognize their mastery.",
        "void whispers dance with delight.",
        "the Rift glows bright with shared joy.",
        "their void-touched nature brings them honor.",
        "the whispers sing praises of accomplishment.",
        "spatial energies crackle with excitement.",
        "the abyss claims this victory as its own.",
        "void-touched strength has proven invaluable.",
        "the Rift radiates approval and warmth.",
        "eldritch laughter echoes through their being.",
        "void energy blazes triumphantly.",
        "the whispers crescendo with celebration.",
        "shadow magic curls in joyful patterns.",
        "their achievement earns the Void's favor.",
        "the abyss grows ever closer, ever prouder.",
        "void-touched power recognized by all.",
        "the whispers approve with ancient knowledge.",
        "spatial magic shimmers with delight.",
        "the Rift's embrace feels warm and proud.",
        "eldritch forces celebrate the victory.",
        "void energy reaches a crescendo of joy.",
        "the whispers sing a song of triumph.",
        "shadow-touched pride swells within them.",
        "the abyss approves, void hunger sated.",
        "void-touched and victorious, fully recognized.",
      },
    },

    {
      id = "voidelf_rest",
      event = "PLAYER_UPDATE_RESTING",
      cooldown = 120,
      category = "flavor",
      channel = "EMOTE",
      messages = {
        "settles in, void whispers growing quiet.",
        "relaxes, allowing the shadows to rest.",
        "finds peace, even the Void needs respite.",
        "meditates, balancing light and shadow within.",
        "rests, the whispers soft and distant.",
        "the abyss recedes, allowing peaceful slumber.",
        "void-touched serenity settles over them.",
        "the whispers hum a lullaby of the Rift.",
        "eldritch dreams begin to form.",
        "the Void loosens its grip, granting rest.",
        "void energy settles into quiet rhythms.",
        "shadow magic wraps around them like a blanket.",
        "the whispers fade to gentle murmuring.",
        "void-touched consciousness grows drowsy.",
        "the abyss waits patiently, content.",
        "eldritch lullabies ease them toward sleep.",
        "void whispers become indistinct, soothing.",
        "the Rift's presence dims to a soft glow.",
        "shadow-touched dreams await them.",
        "the whispers approve of this respite.",
        "void-touched muscles finally relax.",
        "the abyss hums a vibration of peace.",
        "spatial energies slow to resting rhythms.",
        "the Rift sings quiet songs of rest.",
        "eldritch visions of the void begin.",
        "void energy cycles through gentle patterns.",
        "the whispers grow almost motherly in tone.",
        "shadow magic cocoons them in safety.",
        "their void-touched heart beats steadily.",
        "the abyss whispers dreams of distant places.",
        "void-touched mind finds tranquility.",
        "the whispers celebrate this moment of peace.",
        "spatial calm pervades their consciousness.",
        "the Rift releases them to well-earned rest.",
        "eldritch dreams flow like dark water.",
        "void energy pulses in sleeping rhythm.",
        "the whispers become a distant chorus.",
        "shadow-touched sleep embraces them.",
        "the abyss grows quiet, patient, eternal.",
        "void-touched peace, finally achieved and savored.",
      },
    },
  },
})
